In [48]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn.linear_model as skl_lm
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report, precision_score
from sklearn import preprocessing
from sklearn import neighbors

from sklearn import neighbors


from sklearn.cross_validation import train_test_split

import statsmodels.api as sm
import statsmodels.formula.api as smf


%matplotlib inline

from sklearn.metrics import accuracy_score


In [62]:
df = pd.read_csv('../data/Default.csv', index_col=False)


# Note: factorize() returns two objects: a label array and an array with the unique values.
df['default2'] = df.default.factorize()[0]
df['student2'] = df.student.factorize()[0]
df.describe()

        Unnamed: 0       balance        income      default2      student2
count  10000.00000  10000.000000  10000.000000  10000.000000  10000.000000
mean    5000.50000      8.353749  33516.981876      0.033300      0.294400
std     2886.89568      4.837150  13336.639563      0.179428      0.455795
min        1.00000      0.000000    771.967729      0.000000      0.000000
25%     2500.75000      4.817311  21340.462905      0.000000      0.000000
50%     5000.50000      8.236370  34552.644800      0.000000      0.000000
75%     7500.25000     11.663084  43807.729275      0.000000      1.000000
max    10000.00000     26.543226  73554.233500      1.000000      1.000000

In [71]:
# split test train

X = df[['balance','income','student2']]
y = df.default2

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.9, random_state=42)

# linear regresison on balance and incomine

clf = skl_lm.LogisticRegression(penalty = 'l1')

clf.fit(X_train,y_train)
y_hat = clf.predict(X_test)

print(confusion_matrix(y_test, y_hat))
print(accuracy_score(y_test, y_hat) )


knn = neighbors.KNeighborsClassifier(n_neighbors = 2, p = 2)
knn.fit(X_train,y_train)
y_hat = knn.predict(X_test)

print(confusion_matrix(y_test, y_hat))
print(accuracy_score(y_test, y_hat) )


from sklearn.svm import LinearSVC

svc = LinearSVC(C = 0.001)

svc.fit(X_train,y_train)
y_hat = svc.predict(X_test)

print(confusion_matrix(y_test, y_hat))
print(accuracy_score(y_test, y_hat) )


[[8662   34]
 [ 214   90]]
0.972444444444
[[8683   13]
 [ 302    2]]
0.965
[[8696    0]
 [ 304    0]]
0.966222222222


In [72]:
# normalize
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X)



# Mean and std of X
scaler.mean_
scaler.scale_

# Scale and Transform
XX = scaler.transform(X)

X_train, X_test, y_train, y_test = train_test_split( XX, y, test_size=0.9, random_state=42)

# linear regresison on balance and incomine

clf = skl_lm.LogisticRegression(penalty = 'l1')

clf.fit(X_train,y_train)
y_hat = clf.predict(X_test)

print(confusion_matrix(y_test, y_hat))
print(accuracy_score(y_test, y_hat) )

knn = neighbors.KNeighborsClassifier(n_neighbors = 2, p = 2)
knn.fit(X_train,y_train)
y_hat = knn.predict(X_test)

print(confusion_matrix(y_test, y_hat))
print(accuracy_score(y_test, y_hat) )


svc = LinearSVC(C = 0.001)

svc.fit(X_train,y_train)
y_hat = svc.predict(X_test)

print(confusion_matrix(y_test, y_hat))
print(accuracy_score(y_test, y_hat) )


[[8660   36]
 [ 211   93]]
0.972555555556
[[8672   24]
 [ 240   64]]
0.970666666667
[[8696    0]
 [ 304    0]]
0.966222222222


In [61]:
df.describe()

        Unnamed: 0       balance        income      default2      student2
count  10000.00000  10000.000000  10000.000000  10000.000000  10000.000000
mean    5000.50000    835.374886  33516.981876      0.033300      0.294400
std     2886.89568    483.714985  13336.639563      0.179428      0.455795
min        1.00000      0.000000    771.967729      0.000000      0.000000
25%     2500.75000    481.731105  21340.462905      0.000000      0.000000
50%     5000.50000    823.636973  34552.644800      0.000000      0.000000
75%     7500.25000   1166.308387  43807.729275      0.000000      1.000000
max    10000.00000   2654.322576  73554.233500      1.000000      1.000000

In [79]:
from sklearn.metrics import confusion_matrix
y_true = [0,0,0,0,0,1,1,1,1,1]
y_pred = [0,0,0,1,1,0,1,1,1,1]
confusion_matrix(y_true, y_pred)

array([[4, 2],
       [1, 3]])